# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Release build artifacts

on:
  push:
    branches: [ master, main ]
    tags: [ '*' ]

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "8"
          cache: gradle

      - name: Set release version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Build
        run: ./gradlew build

      - name: Update latest tag
        uses: "marvinpinto/action-automatic-releases@latest"
        if: ${{ (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main') }}
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest-packages"
          prerelease: true
          title: "Latest build artifacts"
          files: build/libs/*.jar

      - name: Release named version
        if: ${{ !(github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main') }}
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ env.RELEASE_VERSION }}-packages"
          prerelease: false
          title: "${{ env.RELEASE_VERSION }} build artifacts"
          files: build/libs/*.jar
